fragment PoolFragment on Pool {
  id
  long
  ticks {
    id
    index
    liquidity
  }
}

query getPools($where: Pool_filter) {
  pools(where: $where) {
    ...PoolFragment
  }
}

fragment PositionFragment on Position {
  id
  owner
  tick
  shares
}

query getPositions($where: Position_filter) {
  positions(where: $where) {
    ...PositionFragment
  }
}

fragment ClaimFragment on Claim {
  id
  owner
  exit
  amount
  round
  claimed
  claimer
}

query getClaims($where: Claim_filter) {
  claims(where: $where) {
    ...ClaimFragment
  }
}

fragment PositionClaimFragment on PositionClaim {
  id
  owner
  tick
  burn
  amount
  round
  claimer
  claimed
}

query getPositionClaims($where: PositionClaim_filter) {
  positionClaims(where: $where) {
    ...PositionClaimFragment
  }
}
